
name: Backend Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Backend using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: cd banco_web
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test



  tag-build:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
    - name: Set current date as env variable
      run: echo "NOW=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
        
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'

    - name: Bump version and push tag
      id: tagbuild
      uses: anothrNick/github-tag-action@1.64.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: build-${{ env.NOW }}