name: Production Action

on:
  push:
    tags:
        - 'rel-[0-9]+.[0-9]+.?[0-9]*'
  pull_request:
    tags:
        - 'rel-[0-9]+.[0-9]+.?[0-9]*'
jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: './banco_web'
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Backend build Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'banco_web/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
    - run: npm test

    - name: Zip artifact for deployment
      run: zip prod.zip ./dist/* -r

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: banco_web/prod.zip

  build-front:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: './banco'
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Frontend build Vite ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'banco/package-lock.json'
    - run: npm ci
    - run: npm run build

    - name: Zip frontend artifact for deployment
      run: zip prodFront.zip ./dist/* -r

    - name: Upload frontend artifact for deployment
      uses: actions/upload-artifact@v3
      with:
        name: vite-web-app
        path: banco/prodFront.zip
  
  build-container:
    name: Build container
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action/@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: banco_web
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/banco-api-img:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/banco-api-img:${{ github.run_number }}
