name: Release Action

on:
  push:
    tags:
        - 'rc-[0-9]+.[0-9]+.?[0-9]*'
  pull_request:
    tags:
        - 'rc-[0-9]+.[0-9]+.?[0-9]*'
jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: './banco_web'
    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Backend using Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'banco_web/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
    - run: npm test